config/routes.rb
Rails.application.routes.draw do
  
resources :reviews

root "reviews#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :game, presence: true
  validates :description, length: {minimum: 20}
  validates :score, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :blockchain, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    # list page for reviews
    @reviews = Review.all
  end

  def new
    # form for new review
    @review = Review.new
  end

  def create
    # create new review in database
    @review = Review.new(params.require(:review).permit(:game, :description, :score, :url, :blockchain))

    # save to database
    if @review.save
      redirect_to root_path
      flash[:notice] = "Your Review was Created Successfully!"
    else
      flash[:alert] = "Your Review was NOT Created Successfully! Description must be at least 20 characters long. Score must be between 1 and 10."
      render "new"
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    # delete review from database
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to root_path
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(params.require(:review).permit(:game, :description, :score, :url, :blockchain))

    # save to database
    if @review.save
      redirect_to review_path(@review)
      flash[:notice] = "Your Review was Edited Successfully!"
    else
      flash[:alert] = "Your Review was NOT Edited Successfully!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <div class = "bg-success text-capitalize is-center">
        <%= msg %>
      </div>
    <% else %>
      <div class = "bg-error text-capitalize is-center">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer is-center">
    <h6>Top Blockchain Games Copyright 2022</h6>
  </div>
</footer>

app/views/layouts/_form.html.erb
<%= form_for @review do |f| %>
  <p>
    <%= f.label :game %>
    <%= f.text_field :game %>
    <br>
  </P>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
  </P>
  <p>
    <%= f.label :score %>
    <%= f.number_field :score %>
    <br>
  </P>
  <p>
    <%= f.label :url %>
    <%= f.url_field :url %>
    <br>
  </P>
  <p>
    <div class="field">
      <b><%= f.label :blockchain %></b>
      <br>
      <%= f.label :blockchain, "Ethereum"  %>
      <%= f.radio_button :blockchain, "Etherium" %>
      <%= f.label :blockchain, "Polygon" %>
      <%= f.radio_button :blockchain, "Polygon" %>
      <%= f.label :blockchain, "Solana" %>
      <%= f.radio_button :blockchain, "Solana" %>
    </div>
  </P>
  <div class="is-center">
    <%= f.submit "Save Review" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="header is-center">
    <h1><%= link_to root_path do %>
        <%= image_tag "topblockchaingames.jpg" %>
      <% end %>
    </h1>
  </div>
  <nav class="nav">
    <div class="nav-left">
      <div class="brand">
        <%= link_to 'Top Blockchain Games', root_path %>
      </div>
    </div>
    <div class="nav-right">
      <div class="button outline primary">
        <%= link_to 'Add a Review', new_review_path %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top Blockchain Games - Directory & Reviews for Blockchain Games</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/tinypebblecss@latest">
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h3>Edit your Blockchain Game Review</h3>
<%= render "layouts/form" %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <div class"review">
    <div class="card has-margin-4">
      <b> <%= link_to review.game.capitalize, review_path(review) %> </b>
    </div>
  </div>
<% end %>

app/views/reviews/new.html.erb
<h3>Add your new reviews</h3>
<%= render "layouts/form" %>

app/views/reviews/show.html.erb
<div class="card">
  <header>
    <b><%= @review.game %></b>
  </header>
  <p>
    <%= @review.score %>
  </p>
  <p>
    <%= simple_format @review.description %>
  </p>
  <p>
    <%= @review.blockchain %>
  </p>
  <p>
    <%= link_to @review.game, @review.url %>
  </p>
  <footer>
    <div class="is-right">
      <div class="button secondary">
        <%= link_to 'Cancel', root_path(@review) %>
      </div>
      <div class="button outline secondary">
        <%= link_to 'Edit', edit_review_path(@review) %>
      </div>
      <div class="button error">
        <%= link_to 'Delete', review_path(@review), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </footer>
</div>